export enum EOrientationEvents {
    ORIENTATION_CHANGED = "ORIENTATION_CHANGED",
    ADD_ORIENTATION_BLOCKER = "ADD_ORIENTATION_BLOCKER",
    DELETE_ORIENTATION_BLOCKER = "DELETE_ORIENTATION_BLOCKER",
    DELETE_ALL_ORIENTATION_BLOCKERS = "DELETE_ALL_ORIENTATION_BLOCKERS",
    ALL_BLOCKERS_DELETED = "ALL_BLOCKERS_DELETED"
}