export enum EScreenOrientationWithDevice {
    LANDSCAPE_DESKTOP = "LANDSCAPE_DESKTOP",
    PORTRAIT_DESKTOP = "LANDSCAPE_DESKTOP",
    LANDSCAPE_MOBILE = "LANDSCAPE_MOBILE",
    PORTRAIT_MOBILE = "PORTRAIT_MOBILE",
}